### ISSUE TITLE
Do we have an container image for this project?

### ISSUE THREAD

**Issue by LinuxSuRen** [flexstack/new-dockerfile#6]
**Is your feature request related to a problem? Please describe.**
This is a great project. I hope I can use it in my CI work. Considering I'm using [Argo workflows](https://argoproj.github.io/argo-workflows/) to build my project. So it would be wonderful if there is an image of this project.

And I can help on it if you believe it's worth to do.

**Comment by jaredLunde** [comment]
We don't have an image for it right now, but would love to create one. Your help is appreciated!

**Comment by LinuxSuRen** [comment]
Great. I will do it.
