### ISSUE TITLE
Feel confused why installCMDJSON, _ := json.Marshal(installCMD)

### ISSUE THREAD

**Issue by LinuxSuRen** [flexstack/new-dockerfile#7]
It seems there are some errors here. I'm trying to fix it. But I cannot figure out why `json.Marshal` is needed.

![image](https://github.com/flexstack/new-dockerfile/assets/1450685/b3340139-6c79-4a21-90c7-5aa849a04691)

**Comment by LinuxSuRen** [comment]
When I turned `\u0026\0026` to `&&`, the I got error below:

![image](https://github.com/flexstack/new-dockerfile/assets/1450685/69c33aac-fbdd-45d3-8bd8-14a6bd49ac9f)

**Comment by jaredLunde** [comment]
Thanks for filing this! It's an early stage project so this is very helpful. I am using JSON marshaling for quoting but it might not be necessary. Looking into the second error right now.
